#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
export MAC_ATTENTION_REPO_ROOT="${MAC_ATTENTION_REPO_ROOT:-$REPO_ROOT}"

if [[ -z "${MAC_ATTENTION_ROOT:-}" ]]; then
  if [[ -d "$MAC_ATTENTION_REPO_ROOT/attention" ]]; then
    export MAC_ATTENTION_ROOT="$MAC_ATTENTION_REPO_ROOT/attention"
  else
    export MAC_ATTENTION_ROOT="$MAC_ATTENTION_REPO_ROOT"
  fi
fi
if [[ ! -d "$MAC_ATTENTION_ROOT/src" ]]; then
  echo "MAC_ATTENTION_ROOT does not point to an attention source tree: $MAC_ATTENTION_ROOT" >&2
  return 1 2>/dev/null || exit 1
fi

if [[ -z "${SGLANG_ROOT:-}" ]]; then
  for candidate in \
    "$MAC_ATTENTION_REPO_ROOT/../sglang" \
    "$MAC_ATTENTION_REPO_ROOT/../sglang_official_clean_bbe9c7eeb" \
    "$MAC_ATTENTION_REPO_ROOT/sglang"; do
    if [[ -d "$candidate/python/sglang" ]]; then
      export SGLANG_ROOT="$candidate"
      break
    fi
  done
fi
export MAC_WORKSPACE_BASE="${MAC_WORKSPACE_BASE:-$MAC_ATTENTION_ROOT}"
export TORCH_EXTENSIONS_DIR="${TORCH_EXTENSIONS_DIR:-$MAC_ATTENTION_ROOT/.torch_extensions}"
export TVM_FFI_GPU_BACKEND="${TVM_FFI_GPU_BACKEND:-cuda}"
SGLANG_PYTHONPATH=""
if [[ -n "${SGLANG_ROOT:-}" && -d "$SGLANG_ROOT/python" ]]; then
  SGLANG_PYTHONPATH=":$SGLANG_ROOT/python"
fi
export PYTHONPATH="$MAC_ATTENTION_ROOT/src$SGLANG_PYTHONPATH:${PYTHONPATH:-}"

export MAC_ATTENTION_ENABLE="${MAC_ATTENTION_ENABLE:-1}"
export MAC_ATTENTION_PORTABLE_PLUGIN="${MAC_ATTENTION_PORTABLE_PLUGIN:-1}"
export MAC_ATTENTION_SGLANG_STRICT="${MAC_ATTENTION_SGLANG_STRICT:-1}"
export SGLANG_LAUNCH_MODULE="${SGLANG_LAUNCH_MODULE:-mac_attention.integrations.sglang.launch_server}"

export MAC_THRESHOLD="${MAC_THRESHOLD:-0.45}"
export MAC_LOOKBACK_TOKENS_LEFT="${MAC_LOOKBACK_TOKENS_LEFT:-512}"
export MAC_LOOKBACK_TOKENS_RIGHT="${MAC_LOOKBACK_TOKENS_RIGHT:-0}"
export MAC_GEN_MIN_LIMIT="${MAC_GEN_MIN_LIMIT:-2048}"
export MAC_SEMANTIC_POS_AHEAD="${MAC_SEMANTIC_POS_AHEAD:-256}"

export MAC_DISABLE_CUDA_GRAPH="${MAC_DISABLE_CUDA_GRAPH:-1}"
export MAC_FORCE_PAGED_PREFILL="${MAC_FORCE_PAGED_PREFILL:-1}"
export MAC_PERSISTENT_COOP="${MAC_PERSISTENT_COOP:-1}"
export MAC_PERSISTENT_MAX_CONTEXT="${MAC_PERSISTENT_MAX_CONTEXT:-131072}"
export MAC_PERSISTENT_FAST_WINDOW="${MAC_PERSISTENT_FAST_WINDOW:-8192}"
export MAC_PERSISTENT_TILE_TOKENS="${MAC_PERSISTENT_TILE_TOKENS:-32}"
export MAC_PERSISTENT_STAGE_TOKENS="${MAC_PERSISTENT_STAGE_TOKENS:-64}"
export MAC_PERSISTENT_MATCH_TILE_SLOTS="${MAC_PERSISTENT_MATCH_TILE_SLOTS:-32}"
export MAC_PERSISTENT_DEBUG="${MAC_PERSISTENT_DEBUG:-0}"
export MAC_PERSISTENT_PARTIAL_FP32="${MAC_PERSISTENT_PARTIAL_FP32:-1}"
export MAC_PERSISTENT_CACHE_LAYOUT="${MAC_PERSISTENT_CACHE_LAYOUT:-slot_major}"
export MAC_PERSISTENT_CANDIDATE_MODE="${MAC_PERSISTENT_CANDIDATE_MODE:-last_M}"
export MAC_PERSISTENT_FAST_MATH="${MAC_PERSISTENT_FAST_MATH:-1}"

export MAC_PERSISTENT_PARALLEL_Z2_SCHEDULE="${MAC_PERSISTENT_PARALLEL_Z2_SCHEDULE:-1}"
export MAC_PERSISTENT_MIXED_MISSPACK_Z2="${MAC_PERSISTENT_MIXED_MISSPACK_Z2:-1}"
export MAC_FUSE_HIT_TAIL_IN_MERGE="${MAC_FUSE_HIT_TAIL_IN_MERGE:-0}"
export MAC_PERSISTENT_MIXED_GROUP_FALLBACK="${MAC_PERSISTENT_MIXED_GROUP_FALLBACK:-1}"
export MAC_PERSISTENT_MIXED_EARLY_MISS_DIRECT="${MAC_PERSISTENT_MIXED_EARLY_MISS_DIRECT:-1}"
export MAC_PERSISTENT_HIT_TAIL_GROUP="${MAC_PERSISTENT_HIT_TAIL_GROUP:-1}"
export MAC_PERSISTENT_ALL_HIT_DIRECT="${MAC_PERSISTENT_ALL_HIT_DIRECT:-0}"

export MAC_USE_FUSED_KV_ROPE="${MAC_USE_FUSED_KV_ROPE:-1}"
export MAC_USE_FUSED_Q_PRESERVE_ROPE="${MAC_USE_FUSED_Q_PRESERVE_ROPE:-1}"
