#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAC_TUNING_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MINORTEST_ROOT="${MINORTEST_ROOT:-$(cd "$MAC_TUNING_ROOT/.." && pwd)}"
LONG_BENCH_ROOT="${LONG_BENCH_ROOT:-$MINORTEST_ROOT/LongBench}"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PORTABLE_MAC_PLUGIN=1
export SGLANG_ROOT="${SGLANG_ROOT:-$MINORTEST_ROOT/OFFICIAL_GITHUB/sglang}"
export MAC_ATTENTION_ROOT="${MAC_ATTENTION_ROOT:-$MAC_TUNING_ROOT/attention}"

export MAC_DISABLE_CUDA_GRAPH=0
export LONGBENCH_DISABLE_CUDA_GRAPH=0
export LONGBENCH_CUDA_GRAPH_BS="${LONGBENCH_CUDA_GRAPH_BS:-1}"
export LONGBENCH_DISABLE_PIECEWISE_CUDA_GRAPH="${LONGBENCH_DISABLE_PIECEWISE_CUDA_GRAPH:-1}"
export LONGBENCH_PIECEWISE_CUDA_GRAPH_TOKENS="${LONGBENCH_PIECEWISE_CUDA_GRAPH_TOKENS:-8192}"
export LONGBENCH_SGLANG_EXTRA_ARGS="${LONGBENCH_SGLANG_EXTRA_ARGS:---skip-server-warmup --decode-log-interval 16}"

export MAC_ASYNC_CACHE_UPDATE_SLOTS="${MAC_ASYNC_CACHE_UPDATE_SLOTS:-1}"
export MAC_PERSISTENT_PARALLEL_Z2_SCHEDULE="${MAC_PERSISTENT_PARALLEL_Z2_SCHEDULE:-1}"
export MAC_PERSISTENT_MIXED_MISSPACK_Z2="${MAC_PERSISTENT_MIXED_MISSPACK_Z2:-1}"
export MAC_FUSE_HIT_TAIL_IN_MERGE="${MAC_FUSE_HIT_TAIL_IN_MERGE:-0}"

cd "$LONG_BENCH_ROOT"
exec "$SCRIPT_DIR/autorun_batch_node0_cudagraph_reference.sh" \
  --mode mac \
  --max-concurrent-requests "${MAX_CONCURRENT_REQUESTS:-1}" \
  --port "${BENCH_PORT:-18543}" \
  --model-name "${MODEL_NAME:-Llama-3.1-8B-Instruct}" \
  "$@"
